-- Supabase setup for Tourist Attractions Dashboard in Lenggong Geopark
-- Run this in Supabase SQL Editor.

create table if not exists public.tourist_attractions (
  id bigint generated by default as identity primary key,
  site_name text not null,
  site_type text not null,
  visitor_2022 integer not null default 0,
  visitor_2023 integer not null default 0,
  visitor_2024 integer not null default 0,
  visitor_2025 integer not null default 0,
  average integer not null default 0,
  lat numeric(10, 6) not null,
  lon numeric(10, 6) not null,
  created_at timestamp with time zone default now()
);

truncate table public.tourist_attractions restart identity;

insert into public.tourist_attractions
(site_name, site_type, visitor_2022, visitor_2023, visitor_2024, visitor_2025, average, lat, lon)
values
('Bukit Bunuh / Impak Meteorit Bukit Bunuh', 'Archaeological / meteorite geosite', 3243, 4324, 5160, 5840, 4642, 5.07305, 100.97535),
('Galeri Arkeologi Lembah Lenggong', 'Gallery / main visitor attraction', 17261, 31026, 32385, 31682, 28089, 5.05465, 100.97374),
('Bukit Jawa', 'Archaeological geosite', 1550, 1750, 2207, 2190, 1924, 5.12864, 100.99245),
('Lata Kekabu', 'Waterfall / recreation attraction', 4520, 6567, 6704, 9053, 6711, 5.05039, 100.94480),
('Tasik Raban Lenggong', 'Lake / landscape attraction', 1743, 7388, 15492, 24373, 12249, 5.00207, 100.94463);

-- Enable Row Level Security and allow public read-only access for dashboard display.
alter table public.tourist_attractions enable row level security;

drop policy if exists "Allow public read access to tourist attractions" on public.tourist_attractions;
create policy "Allow public read access to tourist attractions"
on public.tourist_attractions
for select
to anon
using (true);
